name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - run : uname -a
      - run : cat /proc/cpuinfo
      - run : df -h
      - run : cat /etc/os-release
